/**
 * Build script: reads content/site.md and generates src/data/content.ts
 * Run: npx tsx scripts/build-content.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

const src = readFileSync(resolve(root, 'content/site.json'), 'utf-8')
const data = JSON.parse(src)

function stringify(v: unknown, indent = 0): string {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'string') return JSON.stringify(v)
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (Array.isArray(v)) {
    if (v.length === 0) return '[]'
    // Check if all elements are simple (strings/numbers)
    if (v.every(e => typeof e === 'string' || typeof e === 'number')) {
      return JSON.stringify(v)
    }
    const items = v.map(e => `${'  '.repeat(indent + 1)}${stringify(e, indent + 1)}`)
    return `[\n${items.join(',\n')}\n${'  '.repeat(indent)}]`
  }
  if (typeof v === 'object') {
    const entries = Object.entries(v as Record<string, unknown>)
    if (entries.length === 0) return '{}'
    const items = entries.map(([k, val]) => {
      const key = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k)
      return `${'  '.repeat(indent + 1)}${key}: ${stringify(val, indent + 1)}`
    })
    return `{\n${items.join(',\n')}\n${'  '.repeat(indent)}}`
  }
  return String(v)
}

const out = `// ⚠️ AUTO-GENERATED by scripts/build-content.ts — DO NOT EDIT
// Edit content/site.json instead, then re-run the build script.

// ── Types ──────────────────────────────────────────

export interface Stat {
  value: string
  label: string
}

export interface NavLink {
  label: string
  href: string
}

export interface TrustBadge {
  label: string
}

export interface WhyReason {
  title: string
  description: string
  icon: string
}

export interface ServiceCategory {
  slug: string
  title: string
  subtitle: string
  description: string
  image: string
  items: string[]
}

export interface ServiceItem {
  name: string
  description: string
}

export interface ProcessStep {
  title: string
  description: string
}

export interface GalleryImage {
  src: string
  alt: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface ServiceDetail {
  slug: string
  title: string
  subtitle: string
  hero: string
  heroAlt: string
  description: string
  overview: string[]
  items: ServiceItem[]
  process: ProcessStep[]
  equipment: string[]
  gallery: GalleryImage[]
  faq: FAQItem[]
}

export interface ContactItem {
  label: string
  value: string
  href: string
}

export interface FormOption {
  value: string
  label: string
}

export interface ContactFormContent {
  title: string
  subtitle: string
  successTitle: string
  successMessage: string
  resubmitLabel: string
  privacyNote: string
  submitLabel: string
  fields: {
    name: { label: string; placeholder: string }
    phone: { label: string; placeholder: string }
    email: { label: string; placeholder: string }
    service: { label: string; placeholder: string }
    details: { label: string; placeholder: string }
  }
}

export interface FooterLinkGroup {
  title: string
  items: string[]
}

export interface SiteMeta {
  name: string
  tagline: string
  description: string
  domain: string
  email: string
  phone: string
  location: string
  legalName: string
}

// ── Content ────────────────────────────────────────

export const site: SiteMeta = ${stringify(data.site)}

export const navLinks: NavLink[] = ${stringify(data.nav.links)}

export const navCtaText: string = ${JSON.stringify(data.nav.ctaText)}

export const navLogoLetter: string = ${JSON.stringify(data.nav.logoLetter)}

export const heroBackgroundImage: string = ${JSON.stringify(data.hero.backgroundImage)}

export const heroBadgeText: string = ${JSON.stringify(data.hero.badgeText)}

export const heroHeadlineLine1: string = ${JSON.stringify(data.hero.headlineLine1)}

export const heroHeadlineLine2: string = ${JSON.stringify(data.hero.headlineLine2)}

export const heroSubtitle: string = ${JSON.stringify(data.hero.subtitle)}

export const heroPrimaryCta: string = ${JSON.stringify(data.hero.primaryCta)}

export const heroSecondaryCta: string = ${JSON.stringify(data.hero.secondaryCta)}

export const heroTrustBadges: TrustBadge[] = ${stringify(data.hero.trustBadges)}

export const aboutContent = ${stringify(data.about)} as const

export const servicesHome_ = ${stringify(data.servicesHome)} as const

export const serviceDetails: ServiceDetail[] = ${stringify(data.serviceDetails)}

export const whyChooseUs_ = ${stringify(data.whyChooseUs)} as const

export const contactContent = ${stringify(data.contact)} as const

export const footerContent = ${stringify(data.footer)} as const
`

writeFileSync(resolve(root, 'src/data/content.ts'), out)
console.log('✅ Generated src/data/content.ts')
